# compose 파일 버전
version: "3"
services:
  # 서비스 명
  mysql:
    # 사용할 이미지
    image: mysql:8.0
    # 컨테이너 실행 시 재시작
    restart: always
    # 컨테이너명 설정
    container_name: mysql
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - "3306:3306"
    # 환경 변수 설정
    env_file:
      - .env
    # 명렬어 설정
    # command:
    #   - --character-set-server=utf8mb4
    #   - --collation-server=utf8mb4_unicode_ci
    # 볼륨 설정
    volumes:
      - ./data/mysql/:/var/lib/mysql

  app:
    # Dockerfile 위치
    build:
      dockerfile: Dockerfile
    # 애플리케이션 포트 매핑
    ports:
      - "80:3000"
    # 환경 변수 파일 사용 (필요하면)
    env_file:
      - .env
    # 기타 필요한 설정 (볼륨, 네트워크 등)
    volumes:
      - ./app:/app
    depends_on:
      - mysql
